# Generated by Django 4.1.5 on 2023-04-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_labverificationmodel_labprofilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='labprofilemodel',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labprofilemodel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labprofilemodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='labprofilemodel',
            name='files',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='labprofilemodel',
            name='name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='labprofilemodel',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='labprofilemodel',
            name='pincode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labprofilemodel',
            name='reg_no',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='labprofilemodel',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
