# Generated by Django 4.1.5 on 2023-04-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_labprofilemodel_address_labprofilemodel_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=200)),
                ('description', models.TextField(null=True)),
                ('price', models.IntegerField()),
                ('no_tests', models.IntegerField(default=1)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.labmodel')),
            ],
        ),
    ]
