# Generated by Django 4.1.5 on 2023-04-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_packagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemodel',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
