# Generated by Django 4.1.5 on 2023-04-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_appointmentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='stripe_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
