# Generated by Django 4.1.5 on 2023-04-23 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_appointmentmodel_stripe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPayoutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date_last_accessed', models.DateField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.labmodel')),
            ],
        ),
    ]
