# Generated by Django 4.1.5 on 2023-04-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_labpayoutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(default='APPROVED', max_length=255),
        ),
    ]
